//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamousFolks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expertise
    {
        public int ExpId { get; set; }
        public string Expertise1 { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
